# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "talos-systems/talos"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.13.1"

pre_release = false

preface = """\
"""

[notes]

    [notes.caps]
        title = "Kexec and capabilities"
        description = """\
When kexec support is disabled Talos no longer drops Linux capabilities (`CAP_SYS_BOOT` and `CAP_SYS_MODULES`) for child processes.
That is helpful for advanced use-cases like Docker-in-Docker.

If you want to permanently disable kexec and capabilities dropping, pass `kexec_load_disabled=1` argument to the kernel.
For example:

```yaml
install:
  extraKernelArgs:
    - kexec_load_disabled=1
```

Please note that capabilities are dropped before machine configuration is loaded,
so disabling kexec via `machine.sysctls` (like in the section `Reboots via kexec`) will not be enough.
"""


    [notes.kubelet]
        title = "Kubelet"
        description = """\
Kubelet service can now be restarted with `talosctl service kubelet restart`.

Kubelet node IP configuration (`.machine.kubelet.nodeIP.validSubnets`) can now include negative subnet matches (prefixed with `!`).
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/talos-systems/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/talos-systems/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/talos-systems/extras"
