# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "talos-systems/talos"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.12.0"

pre_release = true

preface = """\
"""

[notes]

    [notes.clouds]
        title = "Hetzner, Scaleway and Upcloud"
        description = """\
Talos now natively supports three new cloud platforms:

* [Hetzner](https://www.hetzner.com/)
* [Scaleway](https://www.scaleway.com/en/)
* [Upcloud](https://upcloud.com/)
"""

    [notes.kubespan]
        title = "Cluster Discovery and KubeSpan"
        description = """\
This release of Talos provides some initial support for cluster membership discovery and [KubeSpan](https://www.talos-systems.com/kubespan/).

These new features are not enabled by default.
"""

    [notes.etcd]
        title = "etcd Advertised Address"
        description = """\
The address advertised by etcd can now be controlled with new machine configuration option `machine.etcd.subnet`.
"""

    [notes.windows]
        title = "Windows Suport"
        description = """\
CLI tool talosctl is now built for Windows and published as part of the release.
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/talos-systems/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/talos-systems/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/talos-systems/extras"
