# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "talos-systems/talos"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.13.2"

pre_release = false

preface = """\
"""

[notes]

    [notes.kubelet]
        title = "Kubelet"
        description = """\
Kubelet service can now be restarted with `talosctl service kubelet restart`.

Kubelet node IP configuration (`.machine.kubelet.nodeIP.validSubnets`) can now include negative subnet matches (prefixed with `!`).
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/talos-systems/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/talos-systems/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/talos-systems/extras"
