# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "talos-systems/talos"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.12.0"

pre_release = true

preface = """\
"""

[notes]

    [notes.clouds]
        title = "Hetzner, Scaleway, Upcloud and Vultr"
        description = """\
Talos now natively supports three new cloud platforms:

* [Hetzner](https://www.hetzner.com/)
* [Scaleway](https://www.scaleway.com/en/)
* [Upcloud](https://upcloud.com/)
* [Vultr](https://www.vultr.com/)
"""

    [notes.kexec]
        title = "Reboots via kexec"
        description = """\
Talos now reboots by default via kexec syscall which means BIOS POST process is skipped.
On bare-metal hardware BIOS POST process might take 10-15 minutes, so Talos reboots 10-15 minutes faster on bare-metal.

Kexec support can be disabled with the following change to the machine configuration:

```
machine:
  sysctls:
    kernel.kexec_load_disabled: "1"
```
"""

    [notes.kubespan]
        title = "Cluster Discovery and KubeSpan"
        description = """\
This release of Talos provides initial support for cluster membership discovery and [KubeSpan](https://www.talos-systems.com/kubespan/).

These new features are not enabled by default, to enable them please make following changes to the machine configuration:

```yaml
machine:
  network:
    kubespan:
      enabled: true
cluster:
  discovery:
    enabled: true
```

"""

    [notes.etcd]
        title = "etcd Advertised Address"
        description = """\
The address advertised by etcd can now be controlled with new machine configuration option `machine.etcd.subnet`.
"""

    [notes.windows]
        title = "Windows Suport"
        description = """\
CLI tool talosctl is now built for Windows and published as part of the release.
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/talos-systems/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/talos-systems/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/talos-systems/extras"
